name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/cli@v2.7.0  # Use the latest version available
        with:
          version: '20.10.10'  # Specify the Docker CLI version

      - name: Build Docker image
        run: docker build -t nilu12/flask-app:latest .
        
      - name: Push Docker image to DockerHub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push nilu12/flask-app:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
