name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2.7.0  # Use the latest version available
        with:
          dockerfile: Dockerfile
          context: .

      - name: Build Docker image
        run: docker build -t nilu12/flask-app:latest .
        
      - name: Push Docker image to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push nilu12/flask-app:latest
